kumuluzee:
  name: processing-service
  version: 1.0.0
  env:
    name: dev
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    consul:
      agent: http://consul-1-consul-ui:80

size-config:
  width: 700
  height: 600
