kumuluzee:
  name: processing-service
  version: 1.0.0
  env:
    name: dev
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    consul:
      agent: http://35.187.82.123

size-config:
  width: 700
  height: 600
