kumuluzee:
  name: customer-service
  version: 1.0.0
  env:
    name: dev
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    consul:
      agent: http://35.187.82.123

rest-config:
  string-property: Monday
  boolean-property: true
  integer-property: 23
  encoded-property: ZW5jb2RlZCBwcm9wZXJ0eQ==
